# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeTool < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/be-tool/0.0.3/be-tool_macOS_arm64.zip"
      sha256 "d060df6342e910f2f0d579a7a14259317b8b5636dc11343c5d370b3c89d86ece"

      def install
        bin.install "be-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/be-tool/0.0.3/be-tool_macOS_64-bit.zip"
      sha256 "58221ed422467df9f712533e0f92383cea92c861bf0bcae43bb206621427f6bf"

      def install
        bin.install "be-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/be-tool/0.0.3/be-tool_Tux_arm64.zip"
      sha256 "2818ed4f822789247bc26afa815372e8c156c73f38c23ad6f1272f602c978ed3"

      def install
        bin.install "be-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/be-tool/0.0.3/be-tool_Tux_64-bit.zip"
      sha256 "57374e9386f57a69604755075c11bb7ab3a6069768cd2c6ec4ee62c3f86e458f"

      def install
        bin.install "be-tool"
      end
    end
  end
end
