# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binarymigrationtool < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.1.1/binarymigrationtool_macOS_64-bit.zip"
      sha256 "acf45b4c08cfe626cd8c39d7537d5c1eea1cff2f281b6259cdfeba89f0a9f702"
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.1.1/binarymigrationtool_macOS_arm64.zip"
      sha256 "dc3f11b671ad22eb2390884316ef6d953d7832976016fc47b220966d53747aae"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.1.1/binarymigrationtool_Tux_64-bit.zip"
      sha256 "58b466472a46e8c248353845cf540509807cfbb1a41df768107957b5d3441db5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.1.1/binarymigrationtool_Tux_arm64.zip"
      sha256 "a87c93bf3ca2116c622e991da58cad91e60fcc2f6f61c473c9f62129e864db91"
    end
  end

  def install
    bin.install "binarymigrationtool"
  end
end
