# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binarymigrationtool < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.2.0/binarymigrationtool_macOS_arm64.zip"
      sha256 "3df368995e0126c017cdd3faaea0f273bb37b889112d85061156f3979848f9cb"

      def install
        bin.install "binarymigrationtool"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.2.0/binarymigrationtool_macOS_64-bit.zip"
      sha256 "69d486922e9fd1efb8cf4bf3abbfaecc8a483e7543d235d4224ab360e68ef137"

      def install
        bin.install "binarymigrationtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.2.0/binarymigrationtool_Tux_arm64.zip"
      sha256 "d6236819fc83bf1b49e5e18e5a566b472443c4ecdf1592eee964a08dae406fe4"

      def install
        bin.install "binarymigrationtool"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool/0.2.0/binarymigrationtool_Tux_64-bit.zip"
      sha256 "a204614f7bf3d27b2ddaaf1966bb05a363585f4fbcc69d56f20da5f91a7d9bac"

      def install
        bin.install "binarymigrationtool"
      end
    end
  end
end
