# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BinarymigrationtoolCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool_macOS_64-bit.zip"
    sha256 "8e35fa9d45ee7e584b8c1fc7a7ea01b7907c0d8423f71e03fb37c6529c70e8e0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool_macOS_arm64.zip"
    sha256 "10e6ae17c4d893acbe3df69bbe372056feb707405fbf1cbcffb90c64907bede0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool_Tux_64-bit.zip"
    sha256 "fb2e2947cd84bff14839b33a31069fc09eb9ebc3621004079d9be4e669fbe788"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool_Tux_arm64.zip"
    sha256 "2011337f943fe39fc895b7b157f2f1ded4f4c3f7dbbacce71fdf4b792c531e4e"
  end

  def install
    bin.install "binarymigrationtool"
  end
end
