# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BinarymigrationCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigration-cli/0.1.0/binarymigrationtool_macOS_64-bit.zip"
    sha256 "83cc9865722c6a437067980675ec8ec0408f812106498f979f4ef5dd264325a3"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigration-cli/0.1.0/binarymigrationtool_macOS_arm64.zip"
    sha256 "4124fe955ec67433eb31fbf8f574a14f203b60a405c8b31591e3a8a870b0db45"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigration-cli/0.1.0/binarymigrationtool_Tux_64-bit.zip"
    sha256 "dbb43447d9ed82621082b6f31d8965305cf3580334c3436352e847c6c21fcf13"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigration-cli/0.1.0/binarymigrationtool_Tux_arm64.zip"
    sha256 "a02920d634865325bf71986adaae449c058f3dd5f0365abe85988f95f79c3890"
  end

  def install
    bin.install "binarymigrationtool"
  end
end
