# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BinarymigrationtoolCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool-cli_macOS_64-bit.zip"
    sha256 "b1014d19a749a32fa1daf3a2752549b8840fa738c0d7c3e28ef8cc259616d19b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool-cli_macOS_arm64.zip"
    sha256 "59eed8070b27304df07e4d9d4d39faf3425a4dd89440e22406f77fc3286ea6e9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool-cli_Tux_64-bit.zip"
    sha256 "7001786e3598a6841f5f1a5f5795398dabac1f196b5381b8135c61c87e61e786"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/binarymigrationtool-cli/0.1.0/binarymigrationtool-cli_Tux_arm64.zip"
    sha256 "863bd4855ed8dce56c70b5f105bdc37684121e466d5a2c5d62b7cb88d37352a4"
  end

  def install
    bin.install "binarymigrationtool"
  end
end
