# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewSecurityChecker < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.6/brew-security-checker_macOS_64-bit.zip"
      sha256 "0f0d567e25a00d45b6aad429eed7f6c71a47c007f5d31223ff62471781613690"

      def install
        bin.install "brew-security-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.6/brew-security-checker_macOS_arm64.zip"
      sha256 "ff71ea451bbcf2446862809f7288575dbf4c05a9032eab1f3621df866c99e62c"

      def install
        bin.install "brew-security-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.6/brew-security-checker_Tux_64-bit.zip"
      sha256 "2a23af0d8089895345fe2322e0ef478b5412d0eb2eb4ca48f5c515243718b941"

      def install
        bin.install "brew-security-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.6/brew-security-checker_Tux_arm64.zip"
      sha256 "11151ed8fcfa4702fc5f7b830388fcd9d51eb3c4232760e4d7d197f72866692f"

      def install
        bin.install "brew-security-checker"
      end
    end
  end
end
