# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewSecurityChecker < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.7/brew-security-checker_macOS_64-bit.zip"
      sha256 "0a5a3aff007c361a846c32372b4c2e91580445f8983b6d2a2b09490f3c14dada"

      def install
        bin.install "brew-security-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.7/brew-security-checker_macOS_arm64.zip"
      sha256 "aaf18f3007705d79d2450bc7a54aebac830e0491b47455d8f3212d9ded067c8f"

      def install
        bin.install "brew-security-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.7/brew-security-checker_Tux_64-bit.zip"
      sha256 "8330dbf5a9484e86da687ae9c1fa038f75e074cef7ac78100d26dca87279c4ad"

      def install
        bin.install "brew-security-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.7/brew-security-checker_Tux_arm64.zip"
      sha256 "0eabf1d8736feadea02a0c4692ea417da6558bb838afebd189b0ffae748b73d0"

      def install
        bin.install "brew-security-checker"
      end
    end
  end
end
