# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewSecurityChecker < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.8/brew-security-checker_macOS_64-bit.zip"
      sha256 "1fb5491db4850398c2d621d9cd167026732988c16538d0db90a11718943c6f1e"

      def install
        bin.install "brew-security-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.8/brew-security-checker_macOS_arm64.zip"
      sha256 "71d1dc73d45ffa9861ff5f6122537f791705cffb3c2e754bf0852e2dc85b1f7d"

      def install
        bin.install "brew-security-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.8/brew-security-checker_Tux_64-bit.zip"
      sha256 "c55c5042c1379be87722f7ad124a1f6e8e122bbb3fb68dbc47d3cf029fac201b"

      def install
        bin.install "brew-security-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/brew-security-checker/0.0.8/brew-security-checker_Tux_arm64.zip"
      sha256 "2a8e5a406da30da6cd5009ecd37a7f9d2327be0efd1da725365a0443c30249ba"

      def install
        bin.install "brew-security-checker"
      end
    end
  end
end
