# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrowseS3 < Formula
  desc "CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.1/browse-s3_macOS_64-bit.zip"
    sha256 "9ea9161a2ec0ca9b328a7ea4893648619a206919399333525ae67020af3975a7"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.1/browse-s3_macOS_arm64.zip"
    sha256 "a95404e8cd44e59293fb50ba2b52f93a2c10c625568d82a7a46dbbe1704231c9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.1/browse-s3_Tux_64-bit.zip"
    sha256 "e6eed817a0355b0792d9222f9196b086c78b4ba838bf3270ab2aede1224f75f0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.1/browse-s3_Tux_arm64.zip"
    sha256 "04f4936828dc69fddfbc2e2f1b5da2795ba382368f49a784912fa98bcfdf5cf3"
  end

  def install
    bin.install "browse-s3"
  end
end
