# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrowseS3 < Formula
  desc "CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.2"

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.2/browse-s3_macOS_64-bit.zip"
    sha256 "e9be41100f838eaffa475fe30e906526d1befa65d7a4e2a9cedf68609eeb9e50"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.2/browse-s3_macOS_arm64.zip"
    sha256 "4ac4bcd0a13f1185a7e70d5ce6815405ce23c8ad7c692c97ef73667d7110e3f3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.2/browse-s3_Tux_64-bit.zip"
    sha256 "5fbfb5d3f466eeb347e4e89ef2c8422432dd1321b2494829d842b6599d12ef9b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/browse-s3/0.0.2/browse-s3_Tux_arm64.zip"
    sha256 "1e222f77f566ece3151b1e70b25cfb8fe882a523352731031354cc28708fed2e"
  end

  def install
    bin.install "browse-s3"
  end
end
