# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaImporterCli < Formula
  desc "Handle CCA Importer tasks."
  homepage "https://bitbucket.org/infomaker/cca-importer-cli/"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.10/cca-importer-cli_darwin_amd64.zip"
      sha256 "af5f30c730eecc8cb789bda1583acf15edcf02251dcd74877f4abe8e36f8cd47"

      def install
        bin.install "cca-importer-cli"
        bin.install "cca-importer-copy"
        bin.install "cca-importer-credentials"
        bin.install "cca-importer-info"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.10/cca-importer-cli_darwin_arm64.zip"
      sha256 "29049d26accbae2ab10fa281e9a850df7b425eb04e5db9954b83db1a7837873f"

      def install
        bin.install "cca-importer-cli"
        bin.install "cca-importer-copy"
        bin.install "cca-importer-credentials"
        bin.install "cca-importer-info"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.10/cca-importer-cli_linux_arm64.zip"
      sha256 "d78d061bb4f750e710afc61899ed04f042147f057db48d93ff829fccc8c608b4"

      def install
        bin.install "cca-importer-cli"
        bin.install "cca-importer-copy"
        bin.install "cca-importer-credentials"
        bin.install "cca-importer-info"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.10/cca-importer-cli_linux_amd64.zip"
      sha256 "ea6957463dc21193ce87a4cdc932d85103ab424f5d3e292dab8ce517822f2c32"

      def install
        bin.install "cca-importer-cli"
        bin.install "cca-importer-copy"
        bin.install "cca-importer-credentials"
        bin.install "cca-importer-info"
      end
    end
  end
end
