# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaImporterCli < Formula
  desc "Handle CCA Importer tasks."
  homepage "https://bitbucket.org/infomaker/cca-importer-cli/"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.3/cca-importer-cli_darwin_arm64.zip"
      sha256 "71e28a7f144754e284b4e332a39916611c117ceeff05a0ae54baed7b0a9512a5"

      def install
        bin.install "cca-importer-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.3/cca-importer-cli_darwin_amd64.zip"
      sha256 "b7e0770d6db8a417200ce0691f37775746d7ecb1ddda08cdb734e09461ab3eea"

      def install
        bin.install "cca-importer-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.3/cca-importer-cli_linux_arm64.zip"
      sha256 "5c4966aa756720c7e12ecc5a722fde77ea2951fb84d8301005f600b00a5fd38b"

      def install
        bin.install "cca-importer-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.3/cca-importer-cli_linux_amd64.zip"
      sha256 "19f436e5729939f5cf5b835b4f3cf6e84d763f9c652fc9702afb413283596fea"

      def install
        bin.install "cca-importer-cli"
      end
    end
  end
end
