# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaDownloader < Formula
  desc "Downloads assets using CCA."
  homepage "https://bitbucket.org/infomaker/cca-downloader/"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.2.0/cca-downloader_darwin_amd64.zip"
      sha256 "79dea0ed2f1a18e252fdbbf82deacff343783799c51cad2a42cb1b38bd6c124e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.2.0/cca-downloader_linux_amd64.zip"
      sha256 "ac34ae5b8f0d3cd0a3b05aa1abfedc44ca05c9546009d5dc2d86560edfd5e1d2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.2.0/cca-downloader_linux_arm64.zip"
      sha256 "15bbe37807931f18a2cff1360c6976841cf4882859bd1960640321de786f5799"
    end
  end

  def install
    bin.install "cca-downloader"
  end
end
