# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaDownloader < Formula
  desc "Downloads assets using CCA."
  homepage "https://bitbucket.org/infomaker/cca-downloader/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.3.0/cca-downloader_darwin_amd64.zip"
      sha256 "a0b9c3240207bd527837ecd923adb3834894f8b24945179ea2222c4803fab417"

      def install
        bin.install "cca-downloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.3.0/cca-downloader_darwin_arm64.zip"
      sha256 "b358e9889c72c885f305cc51986465553de841b564d465a73905dec9abcf427a"

      def install
        bin.install "cca-downloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.3.0/cca-downloader_linux_arm64.zip"
      sha256 "664038c813e5257f69b2bf1cf7c3a707923ed3dbc35ddbc26e594e433387f52e"

      def install
        bin.install "cca-downloader"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.3.0/cca-downloader_linux_amd64.zip"
      sha256 "0a416b1475d0d79f26e23bbf64eb167c578c63f659c98433f4c64eb185d4d096"

      def install
        bin.install "cca-downloader"
      end
    end
  end
end
