# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaDownloader < Formula
  desc "Downloads assets using CCA."
  homepage "https://bitbucket.org/infomaker/cca-downloader/"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.2.1/cca-downloader_darwin_amd64.zip"
      sha256 "e445d011f3fc0ab79ef40c3c0bfb73121d95576cc0e3ab6a3e97a1056f1c0bad"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.2.1/cca-downloader_linux_amd64.zip"
      sha256 "755aa65ac1714ab4ec44fa29e25ff1a463738f74b68a2dc9d7808ec43e0fdffc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.2.1/cca-downloader_linux_arm64.zip"
      sha256 "c444cf0a0e70643baf64a952e2bbc47964a428d4f43dcb42d6113efcb8f46fd3"
    end
  end

  def install
    bin.install "cca-downloader"
  end
end
