# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaImporterCli < Formula
  desc "Handle CCA Importer tasks."
  homepage "https://bitbucket.org/infomaker/cca-importer-cli/"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.8/cca-importer-cli_darwin_arm64.zip"
      sha256 "638e55be82b7190be1a0e87d82558230c8d4426ed36acaf586da330890399268"

      def install
        bin.install "cca-importer-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.8/cca-importer-cli_darwin_amd64.zip"
      sha256 "bf11b917a4c194d89b7b3cf939b30998f9b1fc539f03cc92968dcf3a3ab3f5fb"

      def install
        bin.install "cca-importer-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.8/cca-importer-cli_linux_arm64.zip"
      sha256 "ecb911a0e226fbd2a268156d2d40ba4af46c0e41319c2346b02d553729dcd29c"

      def install
        bin.install "cca-importer-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-importer-cli/0.0.8/cca-importer-cli_linux_amd64.zip"
      sha256 "f0674353cd6e6dd18df4015fcef8053728dae42ed08f4265b9f84c3c7be2c66b"

      def install
        bin.install "cca-importer-cli"
      end
    end
  end
end
