# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaUploader < Formula
  desc "Uploads assets using CCA."
  homepage "https://bitbucket.org/infomaker/cca-uploader/"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.1.0/cca_uploader_darwin_amd64.zip"
      sha256 "b5df0a939a599f464718bb6da38d4b604aced694c2a9cc2fccb65244904a4da3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.1.0/cca_uploader_linux_amd64.zip"
      sha256 "270130458263ce9a33e31d96579dd4b69d522c040792ec4cbf1b620ba4754605"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.1.0/cca_uploader_linux_arm64.zip"
      sha256 "788f53586f38c33ae8cc015317b13d8b76dd1b7a745fd812bcecc45bfc93a3ee"
    end
  end

  def install
    bin.install "cca_uploader"
  end
end
