# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcaUploader < Formula
  desc "Uploads assets using CCA."
  homepage "https://bitbucket.org/infomaker/cca-uploader/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.3.0/cca_uploader_darwin_arm64.zip"
      sha256 "072c224d95c9a7c1627d1cf937ec6bbfc20bbfd3ba9e6bfe69a117fb251e9bf3"

      def install
        bin.install "cca_uploader"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.3.0/cca_uploader_darwin_amd64.zip"
      sha256 "036e0ace731b7f71fe07a8d406fc0caae08c29f6e999bd75247420f72741ef58"

      def install
        bin.install "cca_uploader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.3.0/cca_uploader_linux_arm64.zip"
      sha256 "c160f7c35c96ba8e3b55792cebcdd644152f083712642a2b32bcd807cc6116f6"

      def install
        bin.install "cca_uploader"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/cca-uploader/0.3.0/cca_uploader_linux_amd64.zip"
      sha256 "e2248884079403063d4cd3648a63cfb66bea254c392e144d0135c11d05d0ea20"

      def install
        bin.install "cca_uploader"
      end
    end
  end
end
