# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbdynoCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/dbdyno_cli/0.0.2/dashboard-dyno-backup_darwin_arm64.zip"
      sha256 "8f55338cce1faa38f8dcc43b6fb660a8c465ed2dfbb7e526253c9ad7c0d502f5"

      def install
        bin.install "dbdyno_cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/dbdyno_cli/0.0.2/dashboard-dyno-backup_darwin_amd64.zip"
      sha256 "af96faa97ac34d42d377d2687cf37f990f2a8e32d6ce1bc6410cbd62c853f88a"

      def install
        bin.install "dbdyno_cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/dbdyno_cli/0.0.2/dashboard-dyno-backup_linux_arm64.zip"
      sha256 "1fdbc0310ad60be37b771ea57d8b05f1913f0a34c92392f97dab87323c0ebf4d"

      def install
        bin.install "dbdyno_cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/dbdyno_cli/0.0.2/dashboard-dyno-backup_linux_amd64.zip"
      sha256 "cad58114d98018bdcc061075a7ed5877c703842bf633e2f4de0ba32be67a9c13"

      def install
        bin.install "dbdyno_cli"
      end
    end
  end
end
