# This file was generated by GoReleaser. DO NOT EDIT.
class DeployManagerCli < Formula
  desc "Utility that helps with deploy and setup of SaaS services"
  homepage "https://bitbucket.org/infomaker/deploy-manager/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/deploy-manager/0.1.0/deploy-manager_darwin_amd64.zip"
    sha256 "bd4c0fb122c18d70554091bfe38d49180f15adc96228d2b0c5026b9814402ad7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/deploy-manager/0.1.0/deploy-manager_linux_amd64.zip"
    sha256 "facaab3dce01c4a0365b526b85c0e09998fd73907a5f81c17a94e4a477770487"
  end

  def install
    deploy-manager
  end
end
