# This file was generated by GoReleaser. DO NOT EDIT.
class DocCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/doc-cli/0.1.1/doc-cli_macOS_64-bit.zip"
    sha256 "35f5921a6a2cfdd0e69128eabf358e4a88f64d447973087fb1c45095e893ef96"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/doc-cli/0.1.1/doc-cli_Tux_64-bit.zip"
    sha256 "6cac80270e6459ca4c5c2ba8ce2531176c72f53d8ec3545c691c97c5a11d28ab"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
