# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImageengineCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.1.5/imageengine-cli_macOS_64-bit.zip"
    sha256 "3978b63c3e6facb7ff06bdcbd8b55505d6a97f43c2b21c56843ccefd703d2ada"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.1.5/imageengine-cli_macOS_arm64.zip"
    sha256 "89575fe9a02c6c47a79a60195ffa08e0647f5e71f6767db0f9cd613f2b7428c5"
  end

  def install
    bin.install "imageengine-cli"
  end
end
