# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImageengineCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.3.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.3.0/imageengine-cli_macOS_64-bit.zip"
    sha256 "732cd0dbd32c572b6ad09b11b17b84280346292ae9ee2661e96532f935599b92"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.3.0/imageengine-cli_macOS_arm64.zip"
    sha256 "e5189ab37640bf9f95bc0437b9cb86d551cead7b2a68dfa205d7163f968b8f07"
  end

  def install
    bin.install "imageengine-cli"
  end
end
