# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImageengineCli < Formula
  desc "ImageEngine CLI Tools"
  homepage "https://bitbucket.org/infomaker/imageengine-cli/"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.3.2/imageengine-cli_darwin_arm64.zip"
      sha256 "aad1729ad6f8b5b508e85cc4a43fa08641a82cf823c845439e634d51eaeee82b"

      def install
        bin.install "imageengine-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.3.2/imageengine-cli_darwin_amd64.zip"
      sha256 "528bb825fc6e2784fd400278a314e5e47a6b6229cb6f92d2df6648eef6a0c12b"

      def install
        bin.install "imageengine-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.3.2/imageengine-cli_linux_arm64.zip"
      sha256 "413bc924df694e08d5a9f960dc98e37da1b2f5cd9a8d9bcd670ecf53e3ad06a5"

      def install
        bin.install "imageengine-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/imageengine-cli/0.3.2/imageengine-cli_linux_amd64.zip"
      sha256 "695aa8940ae7f87dd5dbcad1c78a088227a499cd26023480b4ca914f446bd6ff"

      def install
        bin.install "imageengine-cli"
      end
    end
  end
end
