# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaGui < Formula
  desc "Ingester Lambda GUI Tool"
  homepage "https://navigaglobal.com"
  version "0.0.3"

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.0.3/ingester-lambda-gui_macOS_64-bit.zip"
    sha256 "0537202daa46c118f01afa3d4be10b3553ea69ecbe7bb8277bb592a7b866dbc1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.0.3/ingester-lambda-gui_Tux_64-bit.zip"
    sha256 "1d21e19b66922beafba4c6b5886c248e5a868dbb082b1f7bf584fc43bc1d6539"
  end

  def install
    bin.install "ingester-gui"
  end
end
