# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LccCli < Formula
  desc "Live Content API CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.0.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/lcc-cli/0.0.6/lcc-go-sdk_macOS_64-bit.zip"
    sha256 "27d24d399b94ec1aceaea08b5bc59769ddd4e705f3f24a052670669cfc691dab"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/lcc-cli/0.0.6/lcc-go-sdk_macOS_arm64.zip"
    sha256 "6d5363a51aeead0a4005032c178ae0f7203991184e1d26f1fe0b48666666bcd9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/lcc-cli/0.0.6/lcc-go-sdk_Tux_64-bit.zip"
    sha256 "ecbaa53d59d45e5caa338d579dd5f0b4ac140524b37724b6df4e7a745889341b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/lcc-cli/0.0.6/lcc-go-sdk_Tux_arm64.zip"
    sha256 "03ec5365fd4de3b6b81319fe46e6ca50df399ec07b164b9f51476981824f4053"
  end

  def install
    bin.install "lcc-cli"
  end
end
