# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Occonf < Formula
  desc "Merges and validates Open Content configuration files."
  homepage "https://bitbucket.org/infomaker/occonf/"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.7.1/occonf_darwin_arm64.zip"
      sha256 "a1ae99cc16a54f6146b55329b3bcde892f860b3c39f3134cf2cc45ed05b9be96"

      def install
        bin.install "occonf"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.7.1/occonf_darwin_amd64.zip"
      sha256 "d25a616945d02e2f03b1b2546cdb4b17219c6f192686d9cb8f9ec53a655590c8"

      def install
        bin.install "occonf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.7.1/occonf_linux_arm64.zip"
      sha256 "ec621416b03653222e265ffcb73ff361d49713d7a56808a776faa0af13292124"

      def install
        bin.install "occonf"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.7.1/occonf_linux_amd64.zip"
      sha256 "a1037df3e97191cda0d4ca40621f206bbaa2193224ee25247af24f187395f0d8"

      def install
        bin.install "occonf"
      end
    end
  end
end
