# This file was generated by GoReleaser. DO NOT EDIT.
class Occonf < Formula
  desc "Merges and validates Open Content configuration files."
  homepage "https://bitbucket.org/infomaker/occonf/"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.4.0/occonf_darwin_amd64.zip"
    sha256 "02c6e63d23668d915b497400a6cd1bb587b7eff697034f7e438cb73c9f78c794"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/occonf/0.4.0/occonf_linux_amd64.zip"
    sha256 "ce759cd7c21589fbadac4fe5b83abaf782fcea286a4e4e0a934772c5091516eb"
  end

  def install
    bin.install "occonf"
  end
end
