# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PagehubClient < Formula
  desc "Upload and download page publication files to Pagehub API."
  homepage "https://bitbucket.org/infomaker/pagehub-client/"
  version "0.14.0-PR6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/pagehub-client/0.14.0-PR6/pagehub-client_darwin_amd64.zip"
      sha256 "0ed96cde21ee66b6c427d934895ff3608150dda6d41188599d17294cf8f53bc8"

      def install
        bin.install "pagehub-client"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/pagehub-client/0.14.0-PR6/pagehub-client_darwin_arm64.zip"
      sha256 "4e4ce57006d73faa30f4318656bf1de6705057f52b059766acb77fd8a63f76bb"

      def install
        bin.install "pagehub-client"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/pagehub-client/0.14.0-PR6/pagehub-client_linux_arm64.zip"
      sha256 "826951d38c9403fc577812bfca804809420c19840a18abe7c6a35180a659bed4"

      def install
        bin.install "pagehub-client"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/pagehub-client/0.14.0-PR6/pagehub-client_linux_amd64.zip"
      sha256 "649049ed99b940cc89467619c9c4aab23189d05e03375f7b7b3f0e95c0f1391b"

      def install
        bin.install "pagehub-client"
      end
    end
  end
end
