# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panurge < Formula
  desc "Panurge utility"
  homepage "https://bitbucket.org/infomaker/panurge/"
  version "1.13.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.13.0/panurge_darwin_arm64.tar.gz"
      sha256 "e6d5ed944bac021e13538c9ca8948d1951a0895bb9d7a88955456b11119610fe"

      def install
        bin.install "panurge"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.13.0/panurge_darwin_amd64.tar.gz"
      sha256 "ea5444c11b1298fc67f606e4b7d882ec40789ce106afe5efac3157c46e209f54"

      def install
        bin.install "panurge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.13.0/panurge_linux_arm64.tar.gz"
      sha256 "76de0e27334df8c29435ba39ea78c418346d43c8263f5cd685835f33a1d0b090"

      def install
        bin.install "panurge"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.13.0/panurge_linux_amd64.tar.gz"
      sha256 "403c230fba8d5c126349bb8687e5026a831feac3bc8d31db1432311630d43ac1"

      def install
        bin.install "panurge"
      end
    end
  end
end
