# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panurge < Formula
  desc "Panurge utility"
  homepage "https://bitbucket.org/infomaker/panurge/"
  version "1.12.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.12.0/panurge_darwin_arm64.tar.gz"
      sha256 "d3f325836aa4eaf02212e17e9383ab2c02b2448d5715c3cf8257a713f9265b1a"

      def install
        bin.install "panurge"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.12.0/panurge_darwin_amd64.tar.gz"
      sha256 "b0d9a60451bc9148add0b29cce77304de159f744c0e19460243a87af39cc67c5"

      def install
        bin.install "panurge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.12.0/panurge_linux_arm64.tar.gz"
      sha256 "958f318661881cf1c5b19b7dfe858121d9dc56ae1bfe785897af024e9bf5eb43"

      def install
        bin.install "panurge"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/panurge/1.12.0/panurge_linux_amd64.tar.gz"
      sha256 "07c1c09a49fcd7cac5d790dfb9e72974893edc5dc670722ee95b9e6ab185451b"

      def install
        bin.install "panurge"
      end
    end
  end
end
