# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panurge < Formula
  desc "Panurge utility"
  homepage "https://github.com/navigacontentlab/panurge"
  version "1.14.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/navigacontentlab/panurge/releases/download/v1.14.0/panurge_darwin_arm64.tar.gz"
      sha256 "0e3f76d848fce74261328f7a6feb6fac3013c17b835116d9c005d3642263913a"

      def install
        bin.install "panurge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/navigacontentlab/panurge/releases/download/v1.14.0/panurge_darwin_amd64.tar.gz"
      sha256 "3a2d178c5adf8432aef7b7226a27968be0b7861b92a13ee0ea6f5268b981727e"

      def install
        bin.install "panurge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/navigacontentlab/panurge/releases/download/v1.14.0/panurge_linux_arm64.tar.gz"
      sha256 "eb554a630370784068169c71c897f4323d5987569ad9e803d4a9e2581c212532"

      def install
        bin.install "panurge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/navigacontentlab/panurge/releases/download/v1.14.0/panurge_linux_amd64.tar.gz"
      sha256 "164e9f80fae8415874f4816ea4448175b740adab0dbbe53eef881198852ec1d3"

      def install
        bin.install "panurge"
      end
    end
  end
end
