# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrintoverviewS3Client < Formula
  desc "Upload and download page publication files to Print Overview API."
  homepage "https://bitbucket.org/infomaker/printoverview-s3-client/"
  version "0.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/printoverview-s3-client/0.5/printoverview-s3-client_darwin_amd64.zip"
      sha256 "9763d3e0e2d0072aee86c7d17c25de6b9e1caa69c8c9158eda306e8b0cecba7b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/printoverview-s3-client/0.5/printoverview-s3-client_linux_amd64.zip"
      sha256 "377f7846d04e7ca22c002b2849c6a2b8494cf2f952de20fd01feef997cbe8d33"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/printoverview-s3-client/0.5/printoverview-s3-client_linux_arm64.zip"
      sha256 "63a13950da03950a9542ad39136e94b09df2baf34748f09344dbac39b4a6ee9d"
    end
  end

  def install
    bin.install "printoverview-s3-client"
  end
end
