# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SandraCli < Formula
  desc "A simple cli."
  homepage "https://bitbucket.org/infomaker/sandra-cli/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.1/sandra-cli_darwin_arm64.zip"
      sha256 "80b378aa65ec78ce16d0816f5487b7c5151a868369552fa133aaa89016743cde"

      def install
        bin.install "sandra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.1/sandra-cli_darwin_amd64.zip"
      sha256 "2faddfd9f64e997cca1eafbc53d516bf6937b87a76518e29ec500a27ae8f8491"

      def install
        bin.install "sandra-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.1/sandra-cli_linux_arm64.zip"
      sha256 "7f1c7b453688c971acb95bb726c13036f7329159c645894b4ac73d63c5713fde"

      def install
        bin.install "sandra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.1/sandra-cli_linux_amd64.zip"
      sha256 "ab23abc8404859ecca1a6393c7f50a5ceca4fac341b3396f2c5be05e2b657f95"

      def install
        bin.install "sandra-cli"
      end
    end
  end
end
