# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SandraCli < Formula
  desc "A simple cli."
  homepage "https://bitbucket.org/infomaker/sandra-cli/"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.2/sandra-cli_darwin_arm64.zip"
      sha256 "1ae4f5dbd200443cc67b098c30921695681941f67dd7f4240c405b18259deaf0"

      def install
        bin.install "sandra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.2/sandra-cli_darwin_amd64.zip"
      sha256 "9faf94af3b39dad92613880f4e03793fa0acbc6cfe42be1802cd28f4bce3ff0e"

      def install
        bin.install "sandra-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.2/sandra-cli_linux_arm64.zip"
      sha256 "88e14e12fd0d8ed49730e7ccb1b7a6ae269c64c0ebf39e0f54cba5752ede84e5"

      def install
        bin.install "sandra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sandra-cli/0.0.2/sandra-cli_linux_amd64.zip"
      sha256 "78227f7e87e830fce15c6d1b116f2e429605ea66fe42e83271887506956b8a47"

      def install
        bin.install "sandra-cli"
      end
    end
  end
end
