# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SebastianoCli < Formula
  desc "A simple cli."
  homepage "https://bitbucket.org/infomaker/sebastiano-cli/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/infomaker/sebastiano-cli/releases/download/v0.0.1/pretty-printer_darwin_arm64.zip"
      sha256 "7b07e5a591ab75a5c2401fe3744adb762f8926a7b4b6c6b25491b56b1f7522fd"

      def install
        bin.install "pretty-printer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/infomaker/sebastiano-cli/releases/download/v0.0.1/pretty-printer_darwin_amd64.zip"
      sha256 "beaf374463d4505aef7094764c1f1934a4b91b5e0a4fcccf0bdabd3145ca8c00"

      def install
        bin.install "pretty-printer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/infomaker/sebastiano-cli/releases/download/v0.0.1/pretty-printer_linux_amd64.zip"
      sha256 "818f093c5c3d36f1fdddac1730b34139563aa05da9a34bd6511d70e858321736"

      def install
        bin.install "pretty-printer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/infomaker/sebastiano-cli/releases/download/v0.0.1/pretty-printer_linux_arm64.zip"
      sha256 "7454d43856ed0f77a702608f901c66665fb214f018870b6e5d5e816c94a1fd3f"

      def install
        bin.install "pretty-printer"
      end
    end
  end
end
