# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SebastianoCli < Formula
  desc "A simple cli."
  homepage "https://bitbucket.org/infomaker/sebastiano-cli/"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sebastiano-cli/0.0.3/sebastiano-cli_darwin_arm64.zip"
      sha256 "25e956a524e5189c7103c638f83128343fe4156d1779b31e8bf80bcaf1d13016"

      def install
        bin.install "sebastiano-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sebastiano-cli/0.0.3/sebastiano-cli_darwin_amd64.zip"
      sha256 "19491a52362ed2f0abced6327fd82f498dfb120ecbf7976cbc38ffed14d12df1"

      def install
        bin.install "sebastiano-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sebastiano-cli/0.0.3/sebastiano-cli_linux_arm64.zip"
      sha256 "bb8acffb04ff774cd71154c66669afe945017c0ee892a315e57fdd0fb252d0fd"

      def install
        bin.install "sebastiano-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/sebastiano-cli/0.0.3/sebastiano-cli_linux_amd64.zip"
      sha256 "286b8458bea79705ffc9d4407d047673e398bb58fa79202c394c5eae14eebb8b"

      def install
        bin.install "sebastiano-cli"
      end
    end
  end
end
