# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Syncbucket < Formula
  desc "Utility for patching up image S3 buckets."
  homepage "https://bitbucket.org/infomaker/syncbucket/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/syncbucket/0.1.1/syncbucket_darwin_amd64.zip"
      sha256 "760d082bf97b98707577797a0f8e219eed5a4c0b670781f13796840452becc25"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/syncbucket/0.1.1/syncbucket_linux_amd64.zip"
      sha256 "871bbccd82548f14787057d6ac6a58ea0bdf53feaa8df6607c3fdc44e556e98c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/syncbucket/0.1.1/syncbucket_linux_arm64.zip"
      sha256 "f18a766ce692fe0df98d77d4e9a9fe822385548535709de9e044e099cb85a5ba"
    end
  end

  def install
    bin.install "syncbucket"
  end
end
