# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Syncbucket < Formula
  desc "Utility for patching up image S3 buckets."
  homepage "https://bitbucket.org/infomaker/syncbucket/"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/syncbucket/0.1.0/syncbucket_darwin_amd64.zip"
      sha256 "a1e52f65b5594b5af970009e51e13881c3c6fe788595d4a6c651117d6d351a44"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/syncbucket/0.1.0/syncbucket_linux_amd64.zip"
      sha256 "3c09a686674aee43e0cb011f724a5486cb21b46812d24a24f4afb206c6bb284e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/syncbucket/0.1.0/syncbucket_linux_arm64.zip"
      sha256 "aa743c35bdbd76f0357e25a4e965a198e8bc3cdd0ffe2e833f103ce8ea51c032"
    end
  end

  def install
    bin.install "syncbucket"
  end
end
