# This file was generated by GoReleaser. DO NOT EDIT.
class Wireingest < Formula
  desc "Administrative tool for wire ingest config."
  homepage "https://bitbucket.org/infomaker/wireingest/"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/wireingest/0.1.2/wireingest_darwin_amd64.zip"
    sha256 "2bb67d8d741a0c783dcac2fa05dab8cbbe3ab98a2bb6c11ddc2f51bb1c8916e8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/wireingest/0.1.2/wireingest_linux_amd64.zip"
    sha256 "1c2107296313be3eca651b65a9e2a1f9d6ba6333c2b479bd1609cac2de7cd101"
  end

  def install
    bin.install "wireingest"
  end
end
