# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WriterSaasAdmin < Formula
  desc "CLI tool for Writer SaaS services."
  homepage "https://bitbucket.org/infomaker/writer-saas-admin/"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.5.0/writer-saas-admin_darwin_amd64.zip"
      sha256 "b3a5c6e6ba5f3aa62ce9bcad47c6297cf0d240c30f533a2b9914f0652765b444"

      def install
        bin.install "writer-saas-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.5.0/writer-saas-admin_darwin_arm64.zip"
      sha256 "12d79e0176ae023b537ec8d7bc802b4a3c58e258133396219e9c8acf9244b8d4"

      def install
        bin.install "writer-saas-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.5.0/writer-saas-admin_linux_amd64.zip"
      sha256 "e1086d83de4c2ad8d6fda37304583664d80c17500c60d26985f4611727f1c1a0"

      def install
        bin.install "writer-saas-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.5.0/writer-saas-admin_linux_arm64.zip"
      sha256 "0c4d64e8f1fc02739184b2d00fe2baab1ae41a674537be10666ef1c8e9299db5"

      def install
        bin.install "writer-saas-admin"
      end
    end
  end
end
