# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WriterSaasAdmin < Formula
  desc "CLI tool for Writer SaaS services."
  homepage "https://bitbucket.org/infomaker/writer-saas-admin/"
  version "1.3.0-rc.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.3.0-rc.1/writer-saas-admin_darwin_arm64.zip"
      sha256 "5bdc094cef36b6b0119d3ad9ed4e1d52aa4fba28b1192b4f173cced896131028"

      def install
        bin.install "writer-saas-admin"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.3.0-rc.1/writer-saas-admin_darwin_amd64.zip"
      sha256 "40d0072a59b4d0dcdf611ef607d02ec71335cfe612d51a987ee3b6c7caa96b87"

      def install
        bin.install "writer-saas-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.3.0-rc.1/writer-saas-admin_linux_arm64.zip"
      sha256 "34a056ae8e5e8886dbc35e31a3f6224a0b0ada04bd86ca09a31036a003ff28b3"

      def install
        bin.install "writer-saas-admin"
      end
    end
    if Hardware::CPU.intel?
      url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/writer-saas-admin/1.3.0-rc.1/writer-saas-admin_linux_amd64.zip"
      sha256 "05b1e8eab0133093528d4aaa90aee56dfb90304ff507c9c7ed895dbf4120a862"

      def install
        bin.install "writer-saas-admin"
      end
    end
  end
end
